services:
  - type: web
    name: apparel-flow-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: MONGO_URI
        fromDatabase: true
    healthCheckPath: /graphql
    healthCheckIntervalSeconds: 30
    minMemory: 512
    maxMemory: 1024
    disk: 1024
    ports:
      - port: 8080
        onOpen: "none"
